name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:
    branches: '**'

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2
        with:
          version: 8.x.x

      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install

      - run: pnpm run test:integ
        env:
          GITHUB_TOKEN: ${{ secrets.INTEG_TEST_ACCESS_TOKEN }}
