name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:
    branches: '**'

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 8.x.x

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - run: pnpm run test:integ
        env:
          GITHUB_TOKEN: ${{ secrets.INTEG_TEST_ACCESS_TOKEN }}
