name: 'Generate JavaScript code and open pull request with it'

on:
  push:
    branches-ignore:
      - 'renovate/*'
      - 'github-actions/generate-js/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          version: 10.x

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install

      - run: pnpm run prepare

      - name: Create pull request with generated JavaScript
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          add-paths: |
            dist/
            pnpm-lock.yaml
          commit-message: Generate JavaScript based on ${{ github.sha }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: github-actions/generate-js/${{ github.ref_name }}
          title: Generate JavaScript for branch `${{ github.ref_name }}`
          body: |
            This pull request is opened automatically and contains generated JavaScript code based on commit ${{ github.sha }}.
