name: 'Generate JavaScript code and open pull request with it'

on:
  push:
    branches-ignore:
      - 'renovate/*'
      - 'github-actions/generate-js/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 8.x.x

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - run: pnpm run prepare

      - name: Get word diff to see changes in dist folder
        id: diff
        run: |
          if ! git diff --quiet dist
          then
            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            echo "GIT_DIFF<<$EOF" >> $GITHUB_OUTPUT
            git diff --word-diff=porcelain --word-diff-regex=. dist | grep '^[+-]' >> $GITHUB_OUTPUT
            echo "$EOF" >> $GITHUB_OUTPUT
          fi

      - name: Create pull request with generated JavaScript
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          add-paths: dist/
          commit-message: Generate JavaScript based on ${{ github.sha }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: github-actions/generate-js/${{ github.ref_name }}
          title: Generate JavaScript for branch `${{ github.ref_name }}`
          body: |
            This pull request is opened automatically and contains generated JavaScript code based on commit ${{ github.sha }}.
